using System.Text;

namespace AubsCraft.Admin.Server.Services;

/// <summary>
/// In-place edits of Minecraft server config files that keep every other line (comments, order, unknown
/// keys) exactly as the server wrote it. Used to point servers at the Velocity proxy (port, online-mode,
/// forwarding secret) without regenerating files the server owns.
/// </summary>
public static class ConfigFiles
{
    /// <summary>Sets key=value in a .properties file (server.properties), appending the key when absent.</summary>
    public static void SetProperty(string path, string key, string value)
    {
        var lines = File.Exists(path) ? File.ReadAllLines(path).ToList() : [];
        var prefix = key + "=";
        var i = lines.FindIndex(l => l.StartsWith(prefix, StringComparison.Ordinal));
        if (i >= 0) lines[i] = prefix + value;
        else lines.Add(prefix + value);
        WriteAllLinesInPlace(path, lines);
    }

    /// <summary>Reads key from a .properties file, or null.</summary>
    public static string? GetProperty(string path, string key)
    {
        if (!File.Exists(path)) return null;
        var prefix = key + "=";
        var line = File.ReadLines(path).FirstOrDefault(l => l.StartsWith(prefix, StringComparison.Ordinal));
        return line?[prefix.Length..];
    }

    /// <summary>
    /// Sets the scalar at <paramref name="keyPath"/> (e.g. proxies, velocity, secret) in a block-style YAML file
    /// such as Paper's paper-global.yml, replacing only that value. <paramref name="yamlValue"/> is written
    /// verbatim (quote strings yourself: <see cref="YamlString"/>). Throws when the path does not exist: these
    /// files are generated by the server, and a missing key means a different format, not something to guess.
    /// </summary>
    /// <summary>
    /// Replaces the entries of a TOP-LEVEL YAML map (e.g. ViaVersion's velocity-servers) with <paramref name="entries"/>
    /// ("key: value", two-space indented). Comments and other keys stay; the file is written in place.
    /// </summary>
    public static void ReplaceYamlMap(string path, string key, IEnumerable<(string Key, string Value)> entries)
    {
        var lines = File.ReadAllLines(path).ToList();
        var start = lines.FindIndex(l => l.StartsWith(key + ":", StringComparison.Ordinal));
        if (start < 0) throw new InvalidDataException($"{Path.GetFileName(path)}: no '{key}'");
        var end = start + 1;
        while (end < lines.Count && (lines[end].StartsWith(' ') || lines[end].StartsWith('\t'))) end++;
        lines.RemoveRange(start + 1, end - start - 1);
        lines[start] = key + ":";
        lines.InsertRange(start + 1, entries.Select(e => $"  {e.Key}: {e.Value}"));
        WriteAllLinesInPlace(path, lines);
    }

    public static void SetYamlScalar(string path, string[] keyPath, string yamlValue)
    {
        var lines = File.ReadAllLines(path).ToList();
        int searchFrom = 0, parentIndent = -1;
        for (int depth = 0; depth < keyPath.Length; depth++)
        {
            var key = keyPath[depth];
            var found = -1;
            for (int i = searchFrom; i < lines.Count; i++)
            {
                var line = lines[i];
                if (line.TrimStart().StartsWith('#') || line.Trim().Length == 0) continue;
                var indent = line.Length - line.TrimStart().Length;
                if (indent <= parentIndent) break; // left the parent block
                if (line.TrimStart().StartsWith(key + ":", StringComparison.Ordinal) &&
                    (depth == 0 ? indent == 0 : indent > parentIndent))
                {
                    found = i;
                    break;
                }
            }
            if (found < 0)
                throw new InvalidDataException($"{Path.GetFileName(path)}: no '{string.Join('.', keyPath[..(depth + 1)])}'");
            if (depth == keyPath.Length - 1)
            {
                var line = lines[found];
                var indent = line.Length - line.TrimStart().Length;
                lines[found] = new string(' ', indent) + key + ": " + yamlValue;
            }
            else
            {
                parentIndent = lines[found].Length - lines[found].TrimStart().Length;
                searchFrom = found + 1;
            }
        }
        WriteAllLinesInPlace(path, lines);
    }

    /// <summary>
    /// Sets `key = value` in a TOML file (velocity.toml). <paramref name="section"/> null = the root table (before
    /// the first [header]). <paramref name="tomlValue"/> is written verbatim (quote strings: <see cref="TomlString"/>).
    /// Throws when the key is not there (the file is generated by Velocity; a missing key means another format).
    /// </summary>
    public static void SetTomlKey(string path, string? section, string key, string tomlValue)
    {
        var lines = File.ReadAllLines(path).ToList();
        var (start, end) = TomlSectionRange(lines, section, path);
        for (int i = start; i < end; i++)
        {
            var t = lines[i].TrimStart();
            if (t.StartsWith(key + " ", StringComparison.Ordinal) || t.StartsWith(key + "=", StringComparison.Ordinal))
            {
                lines[i] = key + " = " + tomlValue;
                WriteAllLinesInPlace(path, lines);
                return;
            }
        }
        throw new InvalidDataException($"{Path.GetFileName(path)}: no '{key}' in [{section ?? "root"}]");
    }

    /// <summary>
    /// Replaces every line of a TOML [section] (its comments too) with <paramref name="body"/> - used for
    /// velocity.toml's [servers] and [forced-hosts], which the panel owns entirely.
    /// </summary>
    public static void ReplaceTomlSection(string path, string section, IEnumerable<string> body)
    {
        var lines = File.ReadAllLines(path).ToList();
        var (start, end) = TomlSectionRange(lines, section, path);
        lines.RemoveRange(start, end - start);
        lines.InsertRange(start, body.Append(""));
        WriteAllLinesInPlace(path, lines);
    }

    /// <summary>Lines [start, end) of a section's body (after its header, up to the next top-level header).</summary>
    private static (int start, int end) TomlSectionRange(List<string> lines, string? section, string path)
    {
        int start;
        if (section == null) start = 0;
        else
        {
            var h = lines.FindIndex(l => l.Trim() == $"[{section}]");
            if (h < 0) throw new InvalidDataException($"{Path.GetFileName(path)}: no [{section}]");
            start = h + 1;
        }
        var end = lines.FindIndex(start, l => l.TrimStart().StartsWith('['));
        return (start, end < 0 ? lines.Count : end);
    }

    /// <summary>A TOML basic string ("..." with \ and " escaped).</summary>
    public static string TomlString(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    /// <summary>A single-quoted YAML string literal ('' escapes a quote).</summary>
    public static string YamlString(string s) => "'" + s.Replace("'", "''") + "'";

    /// <summary>
    /// Rewrites the file IN PLACE. Not write-then-rename: a replaced file takes the panel's owner and mode, and
    /// the server (another user) must still be able to rewrite its own config on start. Callers only edit a
    /// server's files while it is stopped, so nothing reads a half-written file.
    /// </summary>
    private static void WriteAllLinesInPlace(string path, List<string> lines) =>
        File.WriteAllText(path, string.Join('\n', lines) + "\n", new UTF8Encoding(false));
}
